#ifndef PARALLEL_CONFIG_H
#define PARALLEL_CONFIG_H

#include <QtCore/qglobal.h>

#define PARALLEL_VERSION_MAJOR 1
#define PARALLEL_VERSION_MINOR 0
#define PARALLEL_VERSION_PATCH 0
#define PARALLEL_VERSION       PARALLEL_VERSION_CHECK(PARALLEL_VERSION_MAJOR, PARALLEL_VERSION_MINOR, PARALLEL_VERSION_PATCH)

#define PARALLEL_VERSION_STR   "1.0.0"
#define PARALLEL_VERSION_CHECK(major, minor, patch) QT_VERSION_CHECK(major, minor, patch)

#ifdef QT_DEBUG
#   define PARALLEL_DEBUG
#   define PARALLEL_INFO
#   define PARALLEL_WARNING
#   define PARALLEL_CRITICAL
#   define PARALLEL_FATAL
#endif

#endif // PARALLEL_CONFIG_H
